sudo: required
dist: trusty
language: java
jdk: oraclejdk8
before_install:
 - pip install --user codecov
script: mvn package | grep -v Downloading
install: true
after_success:
 - codecov
cache:
 directories:
   - $HOME/.m2
