sudo: required
dist: trusty
language: java
jdk: oraclejdk8
before_install:
 - pip install --user codecov
install: true
before_script: travis_wait 45 ./mvnw install -q -U -DskipTests=true -Dmaven.test.redirectTestOutputToFile=true
script: travis_wait 45 ./mvnw install -q -nsu -Dmaven.test.redirectTestOutputToFile=true
after_success:
 - codecov
cache:
 directories:
   - $HOME/.m2
